name: arg_parser
description: A declarative command-line parser with isolated commands and nested accessor options.
version: 1.0.0
executables:
  task_list: task_list
  yargs_task_list: yargs_task_list
  yargs_command_task_list: yargs_command_task_list
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.12.2

dependencies:
  acanthis: ^1.6.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
