name: mamba
description: A list-defined command-line parser with typed map inputs.
version: 0.4.0
homepage: https://github.com/louiss0/mamba
repository: https://github.com/louiss0/mamba
issue_tracker: https://github.com/louiss0/mamba/issues
topics:
  - command-line
  - parser
  - cli
  - command-line-parser
  - yargs
environment:
  sdk: ^3.12.2

dependencies:
  chalkdart: ^3.1.0
  yaml_writer: ^2.1.0

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.5
  test: ^1.25.6
  zema: ^0.6.0
