import 'dart:io';

import 'package:interact/interact.dart';
import 'package:mamba/command.dart';
import 'package:mamba/errors.dart';

/// Versions a newly scaffolded application executor.
const _applicationVersion = '0.0.0';

/// Creates a project and performs the setup its answers select.
abstract interface class ProjectScaffolder {
  void scaffold(
    String packageName,
    String shortDescription, {
    required bool installDependencies,
    required bool initializeGitRepository,
  });
}

/// Runs a required project-setup command in a project directory.
abstract interface class ProjectProcessRunner {
  void run(String executable, List<String> arguments, String workingDirectory);
}

/// Puts a generated Dart source into the shape `dart format` writes.
///
/// The generators interpolate values of unknown length into fixed positions, so
/// only the formatter knows where the eighty column limit falls.
abstract interface class SourceFormatter {
  void formatSource(String path);
}

/// Asks whether a new project should have its dependencies installed.
abstract interface class InstallPrompt {
  bool confirmsInstallation();
}

/// Asks whether a new project should be initialized as a Git repository.
abstract interface class GitPrompt {
  bool confirmsInitialization();
}

/// The `mamba create` package name that targets the current directory instead
/// of a new child of it.
const _currentDirectoryToken = '.';

/// The Dart package name a scaffolded project is published under.
const _packageNamePattern = r'[a-z][a-z0-9_]*';

/// Hands Claude Code the same instructions without a second copy to drift.
const _claudeInstructionsPointer = '@AGENTS.md\n';

/// The analysis configuration a scaffolded project is held to.
///
/// Without it `dart analyze` reports nothing, because a package with no
/// configuration has no lints to apply.
const _analysisOptions = '''
include: package:lints/recommended.yaml

analyzer:
  language:
    strict-inference: true

linter:
  rules:
    - no_dynamic_casts
    - no_raw_types
    - strict_top_level_inference
''';

/// The ignore rules a scaffolded project receives.
///
/// Taken from the GitHub gitignore template the Toptal API serves for Dart,
/// minus its `pubspec.lock` entry: a command-line application is an
/// application, so its resolved dependency versions belong in version control.
const _gitignore = '''
# Created by https://www.toptal.com/developers/gitignore/api/dart
# Edit at https://www.toptal.com/developers/gitignore?templates=dart

### Dart ###
# See https://www.dartlang.org/guides/libraries/private-files

# Files and directories created by pub
.dart_tool/
.packages
build/

# Directory created by dartdoc
# If you don't generate documentation locally you can remove this line.
doc/api/

# dotenv environment variables file
.env*

# Avoid committing generated Javascript files:
*.dart.js
*.info.json      # Produced by the --dump-info flag.
*.js             # When generated by dart2js. Don't specify *.js if your
                 # project includes source files written in JavaScript.
*.js_
*.js.deps
*.js.map

.flutter-plugins
.flutter-plugins-dependencies

# pubspec.lock is committed: an application pins its dependency versions.

# End of https://www.toptal.com/developers/gitignore/api/dart
''';

/// A single-quoted Dart string literal for [value].
String _dartString(String value) {
  final replacements = <String, String>{
    r'\': r'\\',
    "'": r"\'",
    r'$': r'\$',
    '\r': r'\r',
    '\n': r'\n',
  };
  final escaped = replacements.entries.fold(
    value,
    (source, replacement) =>
        source.replaceAll(replacement.key, replacement.value),
  );

  return "'$escaped'";
}

/// A single-quoted YAML scalar keeps colons, hashes, and leading spaces from
/// changing the meaning of the generated `pubspec.yaml`.
String _yamlString(String value) => "'${value.replaceAll("'", "''")}'";

/// The executable source for a Mamba application.
///
/// It is laid out the way `dart format` writes it, so a generated project is
/// format-clean before anyone edits it.
String _executableSource(String executableName, String shortDescription) =>
    "import 'package:mamba/mamba.dart';\n\n"
    'Future<void> main(List<String> args) => Executor(\n'
    '  ${_dartString(executableName)},\n'
    '  ${_dartString(shortDescription)},\n'
    "  '$_applicationVersion',\n"
    '  [],\n'
    ').create().execute(args);\n';

/// The instructions every scaffolded project receives.
const _agentInstructions = '''
# AGENTS.md

This project is a Mamba command-line application. The `mamba` skill installed
in this project documents the Mamba API; this file documents driving the
`mamba` CLI.

## The mamba CLI

Four commands write files. Run `mamba --help` for the full surface.

| Command | Writes | Use it to |
| --- | --- | --- |
| `mamba command <name>` | `lib/<name>.dart` | Start a command. |
| `mamba command <name> --group` | `lib/<name>.dart` | Start a command that owns child commands. |
| `mamba command <name> --test` | `lib/<name>.dart` and its suite | Start a command with tests. |
| `mamba command <name> --append <file>` | appends to `<file>` | Add a command to an existing file. |
| `mamba test <name>` | `test/<name>_test.dart` | Add a suite for an existing command. |
| `mamba binary <name>` | `bin/<name>.dart` | Add a second executable. |

`<file>` and `--append` require each other, so pass both or neither. `mamba
test` mirrors `lib/a/b.dart` to `test/a/b_test.dart` and rejects a source file
outside `lib/`.

## What not to do

- **Do not hand-write `lib/` or `test/` Dart files.** Scaffold each command and
  each suite with `mamba command` and `mamba test`, so imports, class names,
  and mirrored paths stay correct.
- **Do not leave a scaffolded command unwired.** It runs nothing until its
  instance reaches the executor's command list or its parent's constructor.
- **Do not call `Executor.fake()` from `bin/`.** Call `create()` in the
  executable and keep `fake()` in `test/`.
- **Do not report a rejected invocation by returning a string.** Return the
  success message, and throw `MambaException` when the invocation cannot be
  honoured.
- **Do not expect scaffolding to run the application.** `mamba create` runs
  `dart pub get` and installs the Mamba skills; every other command only writes
  files.
''';

/// The final path segment of [uri], skipping the empty segment a directory's
/// trailing separator leaves behind.
String? _lastPathSegment(Uri uri) =>
    uri.pathSegments.where((segment) => segment.isNotEmpty).lastOrNull;

/// Where a scaffolded project lands and the package name it is published under.
final class ProjectTarget {
  new(this.directory, this.packageName);

  final Directory directory;
  final String packageName;
}

final class DirectoryProjectScaffolder implements ProjectScaffolder {
  new(
    this._parentDirectory, {
    ProjectProcessRunner? processRunner,
    SourceFormatter? sourceFormatter,
  }) : _processRunner = processRunner ?? SystemProjectProcessRunner(),
       _sourceFormatter = sourceFormatter ?? SystemSourceFormatter();

  final Directory _parentDirectory;
  final ProjectProcessRunner _processRunner;
  final SourceFormatter _sourceFormatter;

  @override
  void scaffold(
    String packageName,
    String shortDescription, {
    required bool installDependencies,
    required bool initializeGitRepository,
  }) {
    final target = _createTarget(packageName);

    _createProjectFiles(target, shortDescription);

    if (installDependencies) {
      _installDependencies(target.directory);
    }

    // Agent skills are installed for whoever reads the project next, so they
    // follow the project rather than its Dart dependency graph.
    _installMambaSkills(target.directory);

    if (initializeGitRepository) {
      _initializeGitRepository(target.directory);
    }
  }

  /// Claims the directory a [packageName] names, creating it when the name is
  /// a new child and checking it when the name is the current directory.
  ProjectTarget _createTarget(String packageName) {
    if (packageName != _currentDirectoryToken) {
      final directory = Directory(
        '${_parentDirectory.path}${Platform.pathSeparator}$packageName',
      );

      if (directory.existsSync()) {
        throw MambaException(
          'Cannot create $packageName: the directory already exists.',
        );
      }

      directory.createSync();

      return ProjectTarget(directory, packageName);
    }

    // The current directory is claimed rather than created, so scaffolding into
    // it has to prove nothing already lives there.
    final occupied = _parentDirectory
        .listSync()
        .map((entry) => _lastPathSegment(entry.uri) ?? '')
        .toList();

    if (occupied.isNotEmpty) {
      throw MambaException(
        'Cannot scaffold into the current directory: it already contains '
        '${occupied.join(', ')}.',
      );
    }

    return ProjectTarget(_parentDirectory, _currentDirectoryPackageName());
  }

  /// Reads the package name off the current directory, which has to be one the
  /// generated `pubspec.yaml` and executable can be named after.
  String _currentDirectoryPackageName() {
    final name = _lastPathSegment(_parentDirectory.absolute.uri) ?? '';

    if (!RegExp('^$_packageNamePattern\$').hasMatch(name)) {
      throw MambaException(
        'Cannot scaffold into the current directory: "$name" is not a valid '
        'Dart package name. Pass a name instead of $_currentDirectoryToken.',
      );
    }

    return name;
  }

  void _createProjectFiles(ProjectTarget target, String shortDescription) {
    final projectRoot = target.directory.path;
    final packageName = target.packageName;

    Directory('$projectRoot${Platform.pathSeparator}bin').createSync();

    File('$projectRoot${Platform.pathSeparator}pubspec.yaml').writeAsStringSync(
      'name: $packageName\n'
      'description: ${_yamlString(shortDescription)}\n'
      'environment:\n'
      '  sdk: ^3.13.2\n'
      'dependencies:\n'
      '  mamba: any\n'
      'dev_dependencies:\n'
      '  lints: any\n'
      '  test: any\n',
    );

    File(
      '$projectRoot${Platform.pathSeparator}bin${Platform.pathSeparator}$packageName.dart',
    ).writeAsStringSync(_executableSource(packageName, shortDescription));
    _sourceFormatter.formatSource(
      '$projectRoot${Platform.pathSeparator}bin${Platform.pathSeparator}$packageName.dart',
    );

    File('$projectRoot${Platform.pathSeparator}analysis_options.yaml')
        .writeAsStringSync(_analysisOptions);
    File('$projectRoot${Platform.pathSeparator}.gitignore')
        .writeAsStringSync(_gitignore);
    File('$projectRoot${Platform.pathSeparator}AGENTS.md')
        .writeAsStringSync(_agentInstructions);
    File('$projectRoot${Platform.pathSeparator}CLAUDE.md')
        .writeAsStringSync(_claudeInstructionsPointer);
  }

  void _installDependencies(Directory projectDirectory) {
    _processRunner.run('dart', ['pub', 'get'], projectDirectory.path);
  }

  void _installMambaSkills(Directory projectDirectory) {
    _installMambaSkillsFor(projectDirectory, 'generic');
    _installMambaSkillsFor(projectDirectory, 'claude');
  }

  void _installMambaSkillsFor(Directory projectDirectory, String agent) {
    _processRunner.run('dart', [
      'run',
      'skills@',
      'get',
      '--all',
      '-p',
      'mamba',
      '--agent',
      agent,
    ], projectDirectory.path);
  }

  void _initializeGitRepository(Directory projectDirectory) {
    _processRunner.run('git', ['init'], projectDirectory.path);
  }
}

final class SystemProjectProcessRunner implements ProjectProcessRunner {
  @override
  void run(String executable, List<String> arguments, String workingDirectory) {
    final result = Process.runSync(
      executable,
      arguments,
      workingDirectory: workingDirectory,
    );

    stdout.write(result.stdout);
    stderr.write(result.stderr);

    if (result.exitCode != 0) {
      throw MambaException('Failed to run $executable ${arguments.join(' ')}.');
    }
  }
}

final class SystemSourceFormatter implements SourceFormatter {
  @override
  void formatSource(String path) {
    // A rewrite is the expected outcome, so its exit code is not a failure; only
    // the formatter being unusable is.
    Process.runSync('dart', ['format', path]);
  }
}

final class InteractInstallPrompt implements InstallPrompt {
  /// Installing is the answer that leaves a runnable project, so it is the
  /// answer a bare Enter produces.
  @override
  bool confirmsInstallation() => Confirm(
    prompt: 'Install dependencies?',
    defaultValue: true,
    waitForNewLine: true,
  ).interact();
}

final class InteractGitPrompt implements GitPrompt {
  @override
  bool confirmsInitialization() => Confirm(
    prompt: 'Initialize a Git repository?',
    defaultValue: false,
    waitForNewLine: true,
  ).interact();
}

/// Creates a small Dart package using the current typed command API.
final class CreateProjectCommand extends Command {
  new(
    Directory parentDirectory, {
    ProjectScaffolder? projectScaffolder,
    InstallPrompt? installPrompt,
    GitPrompt? gitPrompt,
  }) : _parentDirectory = parentDirectory,
       _projectScaffolder =
           projectScaffolder ?? DirectoryProjectScaffolder(parentDirectory),
       _installPrompt = installPrompt ?? InteractInstallPrompt(),
       _gitPrompt = gitPrompt ?? InteractGitPrompt(),
       super(
         mandatoryPositionals: [packageName, projectDescription],
         flags: [install, initializeGit],
       );

  static final packageName = NormalPositional(
    'package-name',
    regExp: RegExp('\\.|$_packageNamePattern'),
    description:
        'Name for the new package, or $_currentDirectoryToken to use the '
        'current directory.',
  );
  static final projectDescription = NormalPositional(
    'short-description',
    regExp: RegExp(r'.+'),
  );
  static final install = BooleanFlag(
    'install',
    description: 'Install dependencies without prompting.',
  );
  static final initializeGit = BooleanFlag(
    'git',
    description: 'Initialize a Git repository without prompting.',
  );

  final Directory _parentDirectory;
  final ProjectScaffolder _projectScaffolder;
  final InstallPrompt _installPrompt;
  final GitPrompt _gitPrompt;

  @override
  String get name => 'create';

  @override
  String get shortDescription =>
      'Create a Dart console application using Mamba.';

  @override
  String run(ParsedInputs inputs, List<String> args) {
    final name = inputs.valueOf(packageName);
    final description = inputs.valueOf(projectDescription);

    // A flag answers its own step, so the prompt is only reached when the
    // answer is still open.
    final installsDependencies =
        inputs.valueOf(install) || _installPrompt.confirmsInstallation();
    final initializesGitRepository =
        inputs.valueOf(initializeGit) || _gitPrompt.confirmsInitialization();

    _projectScaffolder.scaffold(
      name,
      description,
      installDependencies: installsDependencies,
      initializeGitRepository: initializesGitRepository,
    );

    final projectPath = name == _currentDirectoryToken
        ? _parentDirectory.path
        : '${_parentDirectory.path}${Platform.pathSeparator}$name';

    return [
      'Created Mamba command-line application in $projectPath.',
      if (!installsDependencies)
        'Run `dart pub get` in $projectPath to install its dependencies.',
    ].join('\n');
  }
}

/// Generates an executable backed by a process-facing Mamba executor.
final class ScaffoldBinaryCommand extends Command {
  new(this._parentDirectory, {SourceFormatter? sourceFormatter})
    : _sourceFormatter = sourceFormatter ?? SystemSourceFormatter(),
      super(mandatoryPositionals: [binaryName]);

  static final binaryName = NormalPositional(
    'name',
    regExp: RegExp(r'[a-z][a-z0-9_]*'),
  );

  final Directory _parentDirectory;
  final SourceFormatter _sourceFormatter;

  @override
  String get name => 'binary';

  @override
  String get shortDescription => 'Create a Mamba executable.';

  @override
  String run(ParsedInputs inputs, List<String> args) {
    final name = inputs.valueOf(binaryName);
    final file = File(
      '${_parentDirectory.path}${Platform.pathSeparator}bin'
      '${Platform.pathSeparator}$name.dart',
    );

    if (file.existsSync()) {
      throw MambaException('Cannot create $name: the file already exists.');
    }

    file.parent.createSync(recursive: true);
    file.writeAsStringSync(
      _executableSource(name, 'A command-line application.'),
    );
    _sourceFormatter.formatSource(file.path);

    return 'Created executable in ${file.path}.';
  }
}

/// Generates a test suite for a scaffolded command.
final class ScaffoldTestCommand extends Command {
  new(this._parentDirectory, {SourceFormatter? sourceFormatter})
    : _sourceFormatter = sourceFormatter ?? SystemSourceFormatter(),
      super(
        mandatoryPositionals: [commandName],
        discretionaryPositionals: [sourcePath],
        flags: [append],
      );

  static final commandName = NormalPositional(
    'name',
    regExp: RegExp(r'[a-z][a-z0-9_]*'),
  );

  static final sourcePath = NormalPositional.optional(
    'file',
    regExp: RegExp(r'.+'),
  );

  static final append = BooleanFlag(
    'append',
    description: 'Add a suite for a command in an existing source file.',
  );

  final Directory _parentDirectory;
  final SourceFormatter _sourceFormatter;

  @override
  String get name => 'test';

  @override
  String get shortDescription => 'Create a test suite for a Mamba command.';

  @override
  String run(ParsedInputs inputs, List<String> args) {
    final name = inputs.valueOf(commandName);
    final targetPath = inputs.valueOf(sourcePath);
    final shouldAppend = inputs.valueOf(append);

    if (targetPath != null && !shouldAppend) {
      throw MambaException('The file argument requires --append.');
    }
    if (targetPath == null && shouldAppend) {
      throw MambaException('--append requires a file argument.');
    }

    final sourceFile = targetPath == null
        ? File(
            '${_parentDirectory.path}${Platform.pathSeparator}lib'
            '${Platform.pathSeparator}$name.dart',
          )
        : File(targetPath);

    final testFile = _createTestSuiteFile(
      name,
      sourceFile,
      appendToSuite: shouldAppend,
    );
    return shouldAppend
        ? 'Added test suite to ${testFile.path}.'
        : 'Created test suite in ${testFile.path}.';
  }

  File _createTestSuiteFile(
    String name,
    File sourceFile, {
    required bool appendToSuite,
  }) {
    if (!sourceFile.existsSync()) {
      throw MambaException(
        'Cannot create a test for $name: ${sourceFile.path} does not exist.',
      );
    }
    final pubspec = File(
      '${_parentDirectory.path}${Platform.pathSeparator}pubspec.yaml',
    );
    final packageMatch = RegExp(
      r'^name:\s*([a-z][a-z0-9_]*)\s*$',
      multiLine: true,
    ).firstMatch(pubspec.existsSync() ? pubspec.readAsStringSync() : '');
    if (packageMatch == null) {
      throw MambaException(
        'Cannot create a test for $name: pubspec.yaml has no valid package name.',
      );
    }

    final packageName = packageMatch.group(1)!;
    final libraryRoot = _parentDirectory.absolute.path.replaceAll('\\', '/');
    final absoluteSourcePath = sourceFile.absolute.path.replaceAll('\\', '/');
    final sourcePrefix = '$libraryRoot/lib/';
    final comparableSource = Platform.isWindows
        ? absoluteSourcePath.toLowerCase()
        : absoluteSourcePath;
    final comparablePrefix = Platform.isWindows
        ? sourcePrefix.toLowerCase()
        : sourcePrefix;
    if (!comparableSource.startsWith(comparablePrefix) ||
        !absoluteSourcePath.endsWith('.dart')) {
      throw MambaException(
        'Cannot create a test for $name: the command file must be under lib.',
      );
    }

    final libraryPath = absoluteSourcePath
        .substring(sourcePrefix.length)
        .replaceAll('\\', '/');
    final testPath = libraryPath.substring(0, libraryPath.length - 5);
    final testFile = File(
      '${_parentDirectory.path}${Platform.pathSeparator}test'
      '${Platform.pathSeparator}${testPath}_test.dart',
    );
    if (!appendToSuite && testFile.existsSync()) {
      throw MambaException(
        'Cannot create $name: the test file already exists.',
      );
    }

    final className = '${name[0].toUpperCase()}${name.substring(1)}Command';
    final suite =
        "  group('$className', () {\n"
        "    test('shows help', () async {\n"
        "      final result = await Executor('test', 'Test.', '1.0.0', [\n"
        '        $className(),\n'
        "      ]).fake().execute(['$name', '--help']);\n\n"
        '      expect(result, isA<MambaSuccessResult>());\n'
        '    });\n'
        '  });\n';

    testFile.parent.createSync(recursive: true);
    if (appendToSuite && testFile.existsSync()) {
      final existing = testFile.readAsStringSync().trimRight();
      final mainClosingBrace = existing.lastIndexOf('}');
      if (mainClosingBrace == -1) {
        throw MambaException(
          'Cannot append $name: ${testFile.path} is not a test suite.',
        );
      }
      testFile.writeAsStringSync(
        '${existing.substring(0, mainClosingBrace)}\n$suite}\n',
      );
    } else {
      // The generated package name decides where its own import sorts, so the
      // directives are ordered rather than written in a fixed sequence.
      final directives = [
        'package:$packageName/$libraryPath',
        'package:mamba/mamba.dart',
        'package:test/test.dart',
      ]..sort();

      testFile.writeAsStringSync(
        '${directives.map((directive) => "import '$directive';").join('\n')}'
        '\n\n'
        'void main() {\n'
        '$suite}\n',
      );
    }

    _sourceFormatter.formatSource(testFile.path);

    return testFile;
  }
}

/// Generates a typed command skeleton.
final class ScaffoldCommand extends Command {
  new(this._parentDirectory, {SourceFormatter? sourceFormatter})
    : _sourceFormatter = sourceFormatter ?? SystemSourceFormatter(),
      super(
        mandatoryPositionals: [commandName],
        discretionaryPositionals: [fileName],
        flags: [group, append, test],
      );

  static final commandName = NormalPositional(
    'name',
    regExp: RegExp(r'[a-z][a-z0-9_]*'),
  );

  static final fileName = NormalPositional.optional(
    'file',
    regExp: RegExp(r'.+'),
  );

  static final group = BooleanFlag(
    'group',
    description: 'Create a group command.',
  );

  static final append = BooleanFlag(
    'append',
    description: 'Append the command to an existing file.',
  );

  static final test = BooleanFlag(
    'test',
    description: 'Create a test suite for the command.',
  );

  final Directory _parentDirectory;
  final SourceFormatter _sourceFormatter;

  @override
  String get name => 'command';

  @override
  String get shortDescription => 'Create a Mamba command.';

  @override
  String run(ParsedInputs inputs, List<String> args) {
    final name = inputs.valueOf(commandName);
    final targetPath = inputs.valueOf(fileName);
    final isGroup = inputs.valueOf(group);
    final shouldAppend = inputs.valueOf(append);
    final shouldCreateTest = inputs.valueOf(test);

    if (targetPath != null && !shouldAppend) {
      throw MambaException('The file argument requires --append.');
    }
    if (targetPath == null && shouldAppend) {
      throw MambaException('--append requires a file argument.');
    }

    final file = targetPath == null
        ? File('${_parentDirectory.path}/lib/$name.dart')
        : File(targetPath);

    if (shouldAppend && !file.existsSync()) {
      throw MambaException('Cannot append $name: ${file.path} does not exist.');
    }
    if (!shouldAppend && file.existsSync()) {
      throw MambaException('Cannot create $name: the file already exists.');
    }

    final className = '${name[0].toUpperCase()}${name.substring(1)}Command';

    final implementation = isGroup
        ? 'final class $className extends GroupCommand {\n'
              '  new() : super([]);\n'
              '\n'
              '  @override\n'
              "  String get name => '$name';\n"
              '\n'
              '  @override\n'
              "  String get shortDescription => 'Describe $name.';\n"
              '}\n'
        : 'final class $className extends Command {\n'
              '  @override\n'
              "  String get name => '$name';\n"
              '\n'
              '  @override\n'
              "  String get shortDescription => 'Describe $name.';\n"
              '\n'
              '  @override\n'
              '  String run(ParsedInputs inputs, List<String> args) =>\n'
              "      'Completed $name.';\n"
              '}\n';

    final previousSource = shouldAppend ? file.readAsStringSync() : null;
    try {
      if (shouldAppend) {
        file.writeAsStringSync('\n$implementation', mode: FileMode.append);
      } else {
        file.parent.createSync(recursive: true);
        file.writeAsStringSync(
          "import 'package:mamba/mamba.dart';\n\n$implementation",
        );
      }

      if (shouldCreateTest) {
        ScaffoldTestCommand(
          _parentDirectory,
          sourceFormatter: _sourceFormatter,
        )._createTestSuiteFile(name, file, appendToSuite: shouldAppend);
      }

      _sourceFormatter.formatSource(file.path);
    } on Object {
      if (previousSource == null) {
        if (file.existsSync()) file.deleteSync();
      } else {
        file.writeAsStringSync(previousSource);
      }
      rethrow;
    }

    return shouldAppend
        ? 'Appended command to ${file.path}.'
        : 'Created command in ${file.path}.';
  }
}
