name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

jobs:
  validate-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
      - run: dart run tool/release.dart --validate-tag "${{ github.ref_name }}"

  publish:
    needs: validate-release
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
